/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bryoag.shopping.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EshoppingCategory service. Represents a row in the &quot;bryoag__EshoppingCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bryoag.shopping.model.impl.EshoppingCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bryoag.shopping.model.impl.EshoppingCategoryImpl}.
 * </p>
 *
 * @author deepakgupta02
 * @see EshoppingCategory
 * @see com.bryoag.shopping.model.impl.EshoppingCategoryImpl
 * @see com.bryoag.shopping.model.impl.EshoppingCategoryModelImpl
 * @generated
 */
public interface EshoppingCategoryModel extends BaseModel<EshoppingCategory>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eshopping category model instance should use the {@link EshoppingCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this eshopping category.
	 *
	 * @return the primary key of this eshopping category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this eshopping category.
	 *
	 * @param primaryKey the primary key of this eshopping category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this eshopping category.
	 *
	 * @return the category ID of this eshopping category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this eshopping category.
	 *
	 * @param categoryId the category ID of this eshopping category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the group ID of this eshopping category.
	 *
	 * @return the group ID of this eshopping category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this eshopping category.
	 *
	 * @param groupId the group ID of this eshopping category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this eshopping category.
	 *
	 * @return the company ID of this eshopping category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this eshopping category.
	 *
	 * @param companyId the company ID of this eshopping category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this eshopping category.
	 *
	 * @return the user ID of this eshopping category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this eshopping category.
	 *
	 * @param userId the user ID of this eshopping category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this eshopping category.
	 *
	 * @return the user uuid of this eshopping category
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this eshopping category.
	 *
	 * @param userUuid the user uuid of this eshopping category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this eshopping category.
	 *
	 * @return the user name of this eshopping category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this eshopping category.
	 *
	 * @param userName the user name of this eshopping category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this eshopping category.
	 *
	 * @return the create date of this eshopping category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this eshopping category.
	 *
	 * @param createDate the create date of this eshopping category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this eshopping category.
	 *
	 * @return the modified date of this eshopping category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this eshopping category.
	 *
	 * @param modifiedDate the modified date of this eshopping category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the parent category ID of this eshopping category.
	 *
	 * @return the parent category ID of this eshopping category
	 */
	public long getParentCategoryId();

	/**
	 * Sets the parent category ID of this eshopping category.
	 *
	 * @param parentCategoryId the parent category ID of this eshopping category
	 */
	public void setParentCategoryId(long parentCategoryId);

	/**
	 * Returns the name of this eshopping category.
	 *
	 * @return the name of this eshopping category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this eshopping category.
	 *
	 * @param name the name of this eshopping category
	 */
	public void setName(String name);

	/**
	 * Returns the description of this eshopping category.
	 *
	 * @return the description of this eshopping category
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this eshopping category.
	 *
	 * @param description the description of this eshopping category
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.bryoag.shopping.model.EshoppingCategory eshoppingCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.bryoag.shopping.model.EshoppingCategory> toCacheModel();

	@Override
	public com.bryoag.shopping.model.EshoppingCategory toEscapedModel();

	@Override
	public com.bryoag.shopping.model.EshoppingCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}