/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bryoag.shopping.image.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Image service. Represents a row in the &quot;skilltailor_Image&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bryoag.shopping.image.model.impl.ImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bryoag.shopping.image.model.impl.ImageImpl}.
 * </p>
 *
 * @author deepakgupta02
 * @see Image
 * @see com.bryoag.shopping.image.model.impl.ImageImpl
 * @see com.bryoag.shopping.image.model.impl.ImageModelImpl
 * @generated
 */
public interface ImageModel extends BaseModel<Image>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a image model instance should use the {@link Image} interface instead.
	 */

	/**
	 * Returns the primary key of this image.
	 *
	 * @return the primary key of this image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this image.
	 *
	 * @param primaryKey the primary key of this image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the image ID of this image.
	 *
	 * @return the image ID of this image
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this image.
	 *
	 * @param imageId the image ID of this image
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the group ID of this image.
	 *
	 * @return the group ID of this image
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this image.
	 *
	 * @param groupId the group ID of this image
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this image.
	 *
	 * @return the company ID of this image
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this image.
	 *
	 * @param companyId the company ID of this image
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this image.
	 *
	 * @return the user ID of this image
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this image.
	 *
	 * @param userId the user ID of this image
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this image.
	 *
	 * @return the user uuid of this image
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this image.
	 *
	 * @param userUuid the user uuid of this image
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this image.
	 *
	 * @return the user name of this image
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this image.
	 *
	 * @param userName the user name of this image
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this image.
	 *
	 * @return the create date of this image
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this image.
	 *
	 * @param createDate the create date of this image
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this image.
	 *
	 * @return the modified date of this image
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this image.
	 *
	 * @param modifiedDate the modified date of this image
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the asset ID of this image.
	 *
	 * @return the asset ID of this image
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this image.
	 *
	 * @param assetId the asset ID of this image
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the asset type of this image.
	 *
	 * @return the asset type of this image
	 */
	@AutoEscape
	public String getAssetType();

	/**
	 * Sets the asset type of this image.
	 *
	 * @param assetType the asset type of this image
	 */
	public void setAssetType(String assetType);

	/**
	 * Returns the small image path of this image.
	 *
	 * @return the small image path of this image
	 */
	@AutoEscape
	public String getSmallImagePath();

	/**
	 * Sets the small image path of this image.
	 *
	 * @param smallImagePath the small image path of this image
	 */
	public void setSmallImagePath(String smallImagePath);

	/**
	 * Returns the medium image path of this image.
	 *
	 * @return the medium image path of this image
	 */
	@AutoEscape
	public String getMediumImagePath();

	/**
	 * Sets the medium image path of this image.
	 *
	 * @param mediumImagePath the medium image path of this image
	 */
	public void setMediumImagePath(String mediumImagePath);

	/**
	 * Returns the large image path of this image.
	 *
	 * @return the large image path of this image
	 */
	@AutoEscape
	public String getLargeImagePath();

	/**
	 * Sets the large image path of this image.
	 *
	 * @param largeImagePath the large image path of this image
	 */
	public void setLargeImagePath(String largeImagePath);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.bryoag.shopping.image.model.Image image);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.bryoag.shopping.image.model.Image> toCacheModel();

	@Override
	public com.bryoag.shopping.image.model.Image toEscapedModel();

	@Override
	public com.bryoag.shopping.image.model.Image toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}