/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bryoag.shopping.service.base;

import com.bryoag.shopping.model.EshoppingCategory;
import com.bryoag.shopping.service.EshoppingCategoryLocalService;
import com.bryoag.shopping.service.persistence.EshoppingCategoryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the eshopping category local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bryoag.shopping.service.impl.EshoppingCategoryLocalServiceImpl}.
 * </p>
 *
 * @author deepakgupta02
 * @see com.bryoag.shopping.service.impl.EshoppingCategoryLocalServiceImpl
 * @see com.bryoag.shopping.service.EshoppingCategoryLocalServiceUtil
 * @generated
 */
public abstract class EshoppingCategoryLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements EshoppingCategoryLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bryoag.shopping.service.EshoppingCategoryLocalServiceUtil} to access the eshopping category local service.
	 */

	/**
	 * Adds the eshopping category to the database. Also notifies the appropriate model listeners.
	 *
	 * @param eshoppingCategory the eshopping category
	 * @return the eshopping category that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EshoppingCategory addEshoppingCategory(
		EshoppingCategory eshoppingCategory) throws SystemException {
		eshoppingCategory.setNew(true);

		return eshoppingCategoryPersistence.update(eshoppingCategory);
	}

	/**
	 * Creates a new eshopping category with the primary key. Does not add the eshopping category to the database.
	 *
	 * @param categoryId the primary key for the new eshopping category
	 * @return the new eshopping category
	 */
	@Override
	public EshoppingCategory createEshoppingCategory(long categoryId) {
		return eshoppingCategoryPersistence.create(categoryId);
	}

	/**
	 * Deletes the eshopping category with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param categoryId the primary key of the eshopping category
	 * @return the eshopping category that was removed
	 * @throws PortalException if a eshopping category with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EshoppingCategory deleteEshoppingCategory(long categoryId)
		throws PortalException, SystemException {
		return eshoppingCategoryPersistence.remove(categoryId);
	}

	/**
	 * Deletes the eshopping category from the database. Also notifies the appropriate model listeners.
	 *
	 * @param eshoppingCategory the eshopping category
	 * @return the eshopping category that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EshoppingCategory deleteEshoppingCategory(
		EshoppingCategory eshoppingCategory) throws SystemException {
		return eshoppingCategoryPersistence.remove(eshoppingCategory);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(EshoppingCategory.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return eshoppingCategoryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.bryoag.shopping.model.impl.EshoppingCategoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return eshoppingCategoryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.bryoag.shopping.model.impl.EshoppingCategoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return eshoppingCategoryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return eshoppingCategoryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return eshoppingCategoryPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public EshoppingCategory fetchEshoppingCategory(long categoryId)
		throws SystemException {
		return eshoppingCategoryPersistence.fetchByPrimaryKey(categoryId);
	}

	/**
	 * Returns the eshopping category with the primary key.
	 *
	 * @param categoryId the primary key of the eshopping category
	 * @return the eshopping category
	 * @throws PortalException if a eshopping category with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public EshoppingCategory getEshoppingCategory(long categoryId)
		throws PortalException, SystemException {
		return eshoppingCategoryPersistence.findByPrimaryKey(categoryId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return eshoppingCategoryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the eshopping categories.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.bryoag.shopping.model.impl.EshoppingCategoryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of eshopping categories
	 * @param end the upper bound of the range of eshopping categories (not inclusive)
	 * @return the range of eshopping categories
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<EshoppingCategory> getEshoppingCategories(int start, int end)
		throws SystemException {
		return eshoppingCategoryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of eshopping categories.
	 *
	 * @return the number of eshopping categories
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getEshoppingCategoriesCount() throws SystemException {
		return eshoppingCategoryPersistence.countAll();
	}

	/**
	 * Updates the eshopping category in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param eshoppingCategory the eshopping category
	 * @return the eshopping category that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EshoppingCategory updateEshoppingCategory(
		EshoppingCategory eshoppingCategory) throws SystemException {
		return eshoppingCategoryPersistence.update(eshoppingCategory);
	}

	/**
	 * Returns the eshopping category local service.
	 *
	 * @return the eshopping category local service
	 */
	public com.bryoag.shopping.service.EshoppingCategoryLocalService getEshoppingCategoryLocalService() {
		return eshoppingCategoryLocalService;
	}

	/**
	 * Sets the eshopping category local service.
	 *
	 * @param eshoppingCategoryLocalService the eshopping category local service
	 */
	public void setEshoppingCategoryLocalService(
		com.bryoag.shopping.service.EshoppingCategoryLocalService eshoppingCategoryLocalService) {
		this.eshoppingCategoryLocalService = eshoppingCategoryLocalService;
	}

	/**
	 * Returns the eshopping category remote service.
	 *
	 * @return the eshopping category remote service
	 */
	public com.bryoag.shopping.service.EshoppingCategoryService getEshoppingCategoryService() {
		return eshoppingCategoryService;
	}

	/**
	 * Sets the eshopping category remote service.
	 *
	 * @param eshoppingCategoryService the eshopping category remote service
	 */
	public void setEshoppingCategoryService(
		com.bryoag.shopping.service.EshoppingCategoryService eshoppingCategoryService) {
		this.eshoppingCategoryService = eshoppingCategoryService;
	}

	/**
	 * Returns the eshopping category persistence.
	 *
	 * @return the eshopping category persistence
	 */
	public EshoppingCategoryPersistence getEshoppingCategoryPersistence() {
		return eshoppingCategoryPersistence;
	}

	/**
	 * Sets the eshopping category persistence.
	 *
	 * @param eshoppingCategoryPersistence the eshopping category persistence
	 */
	public void setEshoppingCategoryPersistence(
		EshoppingCategoryPersistence eshoppingCategoryPersistence) {
		this.eshoppingCategoryPersistence = eshoppingCategoryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.bryoag.shopping.model.EshoppingCategory",
			eshoppingCategoryLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.bryoag.shopping.model.EshoppingCategory");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return EshoppingCategory.class;
	}

	protected String getModelClassName() {
		return EshoppingCategory.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = eshoppingCategoryPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.bryoag.shopping.service.EshoppingCategoryLocalService.class)
	protected com.bryoag.shopping.service.EshoppingCategoryLocalService eshoppingCategoryLocalService;
	@BeanReference(type = com.bryoag.shopping.service.EshoppingCategoryService.class)
	protected com.bryoag.shopping.service.EshoppingCategoryService eshoppingCategoryService;
	@BeanReference(type = EshoppingCategoryPersistence.class)
	protected EshoppingCategoryPersistence eshoppingCategoryPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private EshoppingCategoryLocalServiceClpInvoker _clpInvoker = new EshoppingCategoryLocalServiceClpInvoker();
}