/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.skilltailor.shopping.product.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Product service. Represents a row in the &quot;skilltailor_Product&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.skilltailor.shopping.product.model.impl.ProductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.skilltailor.shopping.product.model.impl.ProductImpl}.
 * </p>
 *
 * @author deepakgupta02
 * @see Product
 * @see com.skilltailor.shopping.product.model.impl.ProductImpl
 * @see com.skilltailor.shopping.product.model.impl.ProductModelImpl
 * @generated
 */
public interface ProductModel extends BaseModel<Product>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product model instance should use the {@link Product} interface instead.
	 */

	/**
	 * Returns the primary key of this product.
	 *
	 * @return the primary key of this product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product.
	 *
	 * @param primaryKey the primary key of this product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the product ID of this product.
	 *
	 * @return the product ID of this product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this product.
	 *
	 * @param productId the product ID of this product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the group ID of this product.
	 *
	 * @return the group ID of this product
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this product.
	 *
	 * @param groupId the group ID of this product
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this product.
	 *
	 * @return the company ID of this product
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product.
	 *
	 * @param companyId the company ID of this product
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product.
	 *
	 * @return the user ID of this product
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this product.
	 *
	 * @param userId the user ID of this product
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product.
	 *
	 * @return the user uuid of this product
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this product.
	 *
	 * @param userUuid the user uuid of this product
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this product.
	 *
	 * @return the user name of this product
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this product.
	 *
	 * @param userName the user name of this product
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this product.
	 *
	 * @return the create date of this product
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product.
	 *
	 * @param createDate the create date of this product
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product.
	 *
	 * @return the modified date of this product
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product.
	 *
	 * @param modifiedDate the modified date of this product
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category ID of this product.
	 *
	 * @return the category ID of this product
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this product.
	 *
	 * @param categoryId the category ID of this product
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the sku of this product.
	 *
	 * @return the sku of this product
	 */
	@AutoEscape
	public String getSku();

	/**
	 * Sets the sku of this product.
	 *
	 * @param sku the sku of this product
	 */
	public void setSku(String sku);

	/**
	 * Returns the product name of this product.
	 *
	 * @return the product name of this product
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this product.
	 *
	 * @param productName the product name of this product
	 */
	public void setProductName(String productName);

	/**
	 * Returns the description of this product.
	 *
	 * @return the description of this product
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this product.
	 *
	 * @param description the description of this product
	 */
	public void setDescription(String description);

	/**
	 * Returns the basic cost of this product.
	 *
	 * @return the basic cost of this product
	 */
	public int getBasicCost();

	/**
	 * Sets the basic cost of this product.
	 *
	 * @param basicCost the basic cost of this product
	 */
	public void setBasicCost(int basicCost);

	/**
	 * Returns the shipping cost of this product.
	 *
	 * @return the shipping cost of this product
	 */
	public int getShippingCost();

	/**
	 * Sets the shipping cost of this product.
	 *
	 * @param shippingCost the shipping cost of this product
	 */
	public void setShippingCost(int shippingCost);

	/**
	 * Returns the total quantity of this product.
	 *
	 * @return the total quantity of this product
	 */
	public int getTotalQuantity();

	/**
	 * Sets the total quantity of this product.
	 *
	 * @param totalQuantity the total quantity of this product
	 */
	public void setTotalQuantity(int totalQuantity);

	/**
	 * Returns the min quantity of this product.
	 *
	 * @return the min quantity of this product
	 */
	public int getMinQuantity();

	/**
	 * Sets the min quantity of this product.
	 *
	 * @param minQuantity the min quantity of this product
	 */
	public void setMinQuantity(int minQuantity);

	/**
	 * Returns the max quantity of this product.
	 *
	 * @return the max quantity of this product
	 */
	public int getMaxQuantity();

	/**
	 * Sets the max quantity of this product.
	 *
	 * @param maxQuantity the max quantity of this product
	 */
	public void setMaxQuantity(int maxQuantity);

	/**
	 * Returns the taxable of this product.
	 *
	 * @return the taxable of this product
	 */
	public Boolean getTaxable();

	/**
	 * Sets the taxable of this product.
	 *
	 * @param taxable the taxable of this product
	 */
	public void setTaxable(Boolean taxable);

	/**
	 * Returns the stock checking of this product.
	 *
	 * @return the stock checking of this product
	 */
	public Boolean getStockChecking();

	/**
	 * Sets the stock checking of this product.
	 *
	 * @param stockChecking the stock checking of this product
	 */
	public void setStockChecking(Boolean stockChecking);

	/**
	 * Returns the discount of this product.
	 *
	 * @return the discount of this product
	 */
	public double getDiscount();

	/**
	 * Sets the discount of this product.
	 *
	 * @param discount the discount of this product
	 */
	public void setDiscount(double discount);

	/**
	 * Returns the image ID of this product.
	 *
	 * @return the image ID of this product
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this product.
	 *
	 * @param imageId the image ID of this product
	 */
	public void setImageId(long imageId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.skilltailor.shopping.product.model.Product product);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.skilltailor.shopping.product.model.Product> toCacheModel();

	@Override
	public com.skilltailor.shopping.product.model.Product toEscapedModel();

	@Override
	public com.skilltailor.shopping.product.model.Product toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}