/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.skilltailor.shopping.product.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import com.skilltailor.shopping.product.model.ProductParts;
import com.skilltailor.shopping.product.service.ProductPartsService;
import com.skilltailor.shopping.product.service.persistence.ProductPartsPersistence;
import com.skilltailor.shopping.product.service.persistence.ProductPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the product parts remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.skilltailor.shopping.product.service.impl.ProductPartsServiceImpl}.
 * </p>
 *
 * @author deepakgupta02
 * @see com.skilltailor.shopping.product.service.impl.ProductPartsServiceImpl
 * @see com.skilltailor.shopping.product.service.ProductPartsServiceUtil
 * @generated
 */
public abstract class ProductPartsServiceBaseImpl extends BaseServiceImpl
	implements ProductPartsService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.skilltailor.shopping.product.service.ProductPartsServiceUtil} to access the product parts remote service.
	 */

	/**
	 * Returns the product local service.
	 *
	 * @return the product local service
	 */
	public com.skilltailor.shopping.product.service.ProductLocalService getProductLocalService() {
		return productLocalService;
	}

	/**
	 * Sets the product local service.
	 *
	 * @param productLocalService the product local service
	 */
	public void setProductLocalService(
		com.skilltailor.shopping.product.service.ProductLocalService productLocalService) {
		this.productLocalService = productLocalService;
	}

	/**
	 * Returns the product remote service.
	 *
	 * @return the product remote service
	 */
	public com.skilltailor.shopping.product.service.ProductService getProductService() {
		return productService;
	}

	/**
	 * Sets the product remote service.
	 *
	 * @param productService the product remote service
	 */
	public void setProductService(
		com.skilltailor.shopping.product.service.ProductService productService) {
		this.productService = productService;
	}

	/**
	 * Returns the product persistence.
	 *
	 * @return the product persistence
	 */
	public ProductPersistence getProductPersistence() {
		return productPersistence;
	}

	/**
	 * Sets the product persistence.
	 *
	 * @param productPersistence the product persistence
	 */
	public void setProductPersistence(ProductPersistence productPersistence) {
		this.productPersistence = productPersistence;
	}

	/**
	 * Returns the product parts local service.
	 *
	 * @return the product parts local service
	 */
	public com.skilltailor.shopping.product.service.ProductPartsLocalService getProductPartsLocalService() {
		return productPartsLocalService;
	}

	/**
	 * Sets the product parts local service.
	 *
	 * @param productPartsLocalService the product parts local service
	 */
	public void setProductPartsLocalService(
		com.skilltailor.shopping.product.service.ProductPartsLocalService productPartsLocalService) {
		this.productPartsLocalService = productPartsLocalService;
	}

	/**
	 * Returns the product parts remote service.
	 *
	 * @return the product parts remote service
	 */
	public com.skilltailor.shopping.product.service.ProductPartsService getProductPartsService() {
		return productPartsService;
	}

	/**
	 * Sets the product parts remote service.
	 *
	 * @param productPartsService the product parts remote service
	 */
	public void setProductPartsService(
		com.skilltailor.shopping.product.service.ProductPartsService productPartsService) {
		this.productPartsService = productPartsService;
	}

	/**
	 * Returns the product parts persistence.
	 *
	 * @return the product parts persistence
	 */
	public ProductPartsPersistence getProductPartsPersistence() {
		return productPartsPersistence;
	}

	/**
	 * Sets the product parts persistence.
	 *
	 * @param productPartsPersistence the product parts persistence
	 */
	public void setProductPartsPersistence(
		ProductPartsPersistence productPartsPersistence) {
		this.productPartsPersistence = productPartsPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ProductParts.class;
	}

	protected String getModelClassName() {
		return ProductParts.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = productPartsPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.skilltailor.shopping.product.service.ProductLocalService.class)
	protected com.skilltailor.shopping.product.service.ProductLocalService productLocalService;
	@BeanReference(type = com.skilltailor.shopping.product.service.ProductService.class)
	protected com.skilltailor.shopping.product.service.ProductService productService;
	@BeanReference(type = ProductPersistence.class)
	protected ProductPersistence productPersistence;
	@BeanReference(type = com.skilltailor.shopping.product.service.ProductPartsLocalService.class)
	protected com.skilltailor.shopping.product.service.ProductPartsLocalService productPartsLocalService;
	@BeanReference(type = com.skilltailor.shopping.product.service.ProductPartsService.class)
	protected com.skilltailor.shopping.product.service.ProductPartsService productPartsService;
	@BeanReference(type = ProductPartsPersistence.class)
	protected ProductPartsPersistence productPartsPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ProductPartsServiceClpInvoker _clpInvoker = new ProductPartsServiceClpInvoker();
}